api: fix model builder watcher exception
This change fixes the following runtime exception:
  thread '<unnamed>' panicked at crates/web-service/src/worker.rs:229:21:
  Cannot block the current thread from within a runtime. This happens because a function attempted to block the current thread while the thread is being used to drive asynchronous tasks.